### ISSUE TITLE
Purpose of script/remap-caps-lock-to-control

### ISSUE THREAD

**Issue by samuelmasuy** [jasonrudolph/ControlEscape.spoon#1]
First of all, I really appreciate what you have done here, I could finally upgrade to Sierra. 
In my case, the only issue I have encountered, is that the remapping did not survive a restart of the machine. I had to re-run at startup both `setup` and `remap-caps-lock-to-control` scripts for some reason.
The solution that I found is to simply remap <kbd>caps lock</kbd> to <kbd>control</kbd> in System Preferences > Keyboard > Modifier Keys...

**Comment by jasonrudolph** [comment]
> the only issue I have encountered, is that the remapping did not survive a restart of the machine.

Oh, man. Thanks for letting me know. I definitely should have tested that. How embarrassing. 🤦

> The solution that I found is to simply remap <kbd>caps lock</kbd> to <kbd>control</kbd> in System Preferences > Keyboard > Modifier Keys...

Yeah. That seems like the way to go for now:

<img width="780" alt="screenshot" src="https://user-images.githubusercontent.com/2988/27111039-7f620442-507b-11e7-9bcf-93d46e14af13.png">

For what it's worth, I added [`script/remap-caps-lock-to-control`](https://github.com/jasonrudolph/ControlEscape.spoon/blob/v1.0.0/script/remap-caps-lock-to-control) in hopes that people could get everything set up and installed without having to leave the terminal. But, since the effects of that script get lost after restarting macOS, I'll either need to find a different terminal-based solution, or I'll have to instruct people to briefly leave the warmth of the keyboard in order to click around in System Preferences for a bit. 🖱
