### ISSUE TITLE
How to use capslock after changing it to escape/control?

### ISSUE THREAD

**Issue by wenfangdu** [jasonrudolph/ControlEscape.spoon#14]
Thank you for making this spoon, after following the guide, I did get the capslock to escape/control mapping working, however, I can't use the real capslock anymore, is there any way to get around this? Ideally, capslock should be triggered via a shortcut, not a single key press.

**Comment by jasonrudolph** [comment]
👋 @wenfangdu: Thanks for checking out this spoon. 

This [<kbd>caps lock</kbd> configuration is optional](https://github.com/jasonrudolph/ControlEscape.spoon/tree/cc5749931afe61c299ac8371230ec77a870b775a#optional-a-more-useful-caps-lock-key), and is designed for folks are willing to entirely give up the traditional use of the <kbd>caps lock</kbd> key, so that you can instead tap it for <kbd>escape</kbd> and hold it for <kbd>control</kbd>.

So, one option for you is to _not_ use the optional <kbd>caps lock</kbd> configuration. Instead, you would tap your <kbd>control</kbd> key for <kbd>escape</kbd> and hold it for <kbd>control</kbd>.

Another option would be to explore alternative ways to trigger <kbd>caps lock</kbd> via additional automation (e.g., double-tapping <kbd>shift</kbd> for <kbd>caps lock</kbd>: https://dustin.lol/post/2021/remapping-caps-lock).

I hope this helps.
